---
title: "Process Simple For-Rev"
author: "Matthew Berginski"
output: github_document
---

```{r setup, include=FALSE}
library(tidyverse)
library(readxl)
library(here)
library(BerginskiRMisc)
library(cowplot)
library(janitor)

knitr::opts_chunk$set(dev=c("svg"),dpi=600)
```

## Read In Data

```{r read_in_curve_data}

process_excel_sheet <- function(excel_data_file, sheet = 1) {

  excel_data = read_excel(excel_data_file,sheet = sheet)

  split_header = str_split(names(excel_data)[1],"-")
  kinase = split_header[[1]][1]

  split_peptide_type = str_split(split_header[[1]][2]," ")

  peptide = split_peptide_type[[1]][1]
  curve_type = split_peptide_type[[1]][2]

  excel_data = read_excel(excel_data_file,sheet = sheet,skip=1) %>%
    select(Replicate,Ion,Theor_conc,Meas_conc) %>%
    mutate(Meas_conc = as.numeric(Meas_conc)) %>%
    mutate(kinase=kinase,curve_type=curve_type,peptide=peptide)
  return(excel_data)
}

deep_dive_data = process_excel_sheet(here('simple_XY/Deep Dive Kinome plot data.xlsx'),sheet = 1)

for (i in 2:length(excel_sheets(here('simple_XY/Deep Dive Kinome plot data.xlsx')))) {
  deep_dive_data = rbind(deep_dive_data,
                         process_excel_sheet(here('simple_XY/Deep Dive Kinome plot data.xlsx'),sheet = i))
}

for (i in 1:length(excel_sheets(here('simple_XY/072919 file set/Dark kinome set 1 of 4 reverse plot data.xlsx')))) {
  deep_dive_data = rbind(deep_dive_data,
                         process_excel_sheet(here('simple_XY/072919 file set/Dark kinome set 1 of 4 reverse plot data.xlsx'),sheet = i))
}

for (i in 1:length(excel_sheets(here('simple_XY/072919 file set/Dark Kinome set 2 of 4 reverse plot data.xlsx')))) {
  deep_dive_data = rbind(deep_dive_data,
                         process_excel_sheet(here('simple_XY/072919 file set/Dark Kinome set 2 of 4 reverse plot data.xlsx'),sheet = i))
}

for (i in 1:length(excel_sheets(here('simple_XY/072919 file set/Dark Kinome set 3 of 4 reverse plot data.xlsx')))) {
  deep_dive_data = rbind(deep_dive_data,
                         process_excel_sheet(here('simple_XY/072919 file set/Dark Kinome set 3 of 4 reverse plot data.xlsx'),sheet = i))
}

for (i in 1:length(excel_sheets(here('simple_XY/072919 file set/Dark Kinome set 4 of 4 reverse plot data.xlsx')))) {
  deep_dive_data = rbind(deep_dive_data,
                         process_excel_sheet(here('simple_XY/072919 file set/Dark Kinome set 4 of 4 reverse plot data.xlsx'),sheet = i))
}
```

```{r read_in_curve_summary}
# curve_summary = read_excel(here('simple_XY/Deep Dive plot parameters.xlsx')) %>%
#   clean_names() %>%
#   mutate(peptide_start = str_extract(peptide,'.{3}')) %>%
#   filter(!is.na(gene_symbol)) %>%
#   rename(correlation_plot_slope = reverse_curve_slope,
#          correlation_plot_intercept = reverse_curve_y_intercept,
#          response_curve_slope = forward_curve_slope,
#          response_curve_intercept = forward_curve_y_intercept)
# 
# curve_summary$correlation_plot_slope = as.numeric(curve_summary$correlation_plot_slope)
# curve_summary$correlation_plot_intercept = as.numeric(curve_summary$correlation_plot_intercept)
# curve_summary$response_curve_slope = as.numeric(curve_summary$response_curve_slope)
# curve_summary$response_curve_intercept = as.numeric(curve_summary$response_curve_intercept)

# temp = deep_dive_data %>% left_join(curve_summary)

curve_summary = read_excel(here('simple_XY/072919 file set/PARM TABLE.xlsx'),skip=1) %>%
  clean_names() %>%
  #clear out the lines without data present
  filter(!is.na(protein_name)) %>%
  mutate(lod_fmol_2 = as.numeric(lod_fmol_2),
         loq_fmol_3 = as.numeric(loq_fmol_3)) %>%
  #rename vars to help with matching and make a cleaner name
  rename(lod = lod_fmol_2, peptide = peptide_sequence) %>%
  #manually correct the first peptide marked with the 1
  mutate(peptide = ifelse(peptide == "DTGELVALK1", "DTGELVALK",peptide)) %>%
  identity()

responce_curve_data = as.tibble(str_match(curve_summary$calibration_curve_equation,'y=(-)*([^x]+)x\\+*(.*)'))
colnames(responce_curve_data) <- c("matched_eq","slope_sign","correlation_plot_slope","correlation_plot_intercept")
responce_curve_data = responce_curve_data %>%
  mutate(correlation_plot_slope = as.numeric(correlation_plot_slope)) %>%
  mutate(correlation_plot_intercept = as.numeric(correlation_plot_intercept))

curve_summary$correlation_plot_slope = responce_curve_data$correlation_plot_slope
curve_summary$correlation_plot_intercept = responce_curve_data$correlation_plot_intercept

deep_dive_data = deep_dive_data %>% 
  left_join(curve_summary %>% select(peptide,lod,correlation_plot_slope,correlation_plot_intercept))
```

```{r write_curve_summary}
curve_summary_output = read_excel(here('simple_XY/072919 file set/PARM TABLE.xlsx'),skip=1) %>%
  #toss out any protein names that are NA, these are the notes at the end of the table
  filter(!is.na(`Protein Name`)) %>%
  
  #round the LOQ value as appears in the spreadsheet
  mutate(`LOQ (fmol)3` = as.numeric(`LOQ (fmol)3`)) %>%
  mutate(`LOQ (fmol)3` = signif(`LOQ (fmol)3`,4)) %>%
  
  mutate(`LOD (fmol)2` = as.numeric(`LOD (fmol)2`)) %>%
  mutate(`LOD (fmol)2` = signif(`LOD (fmol)2`,4)) %>%
  
  #We need the last character of the peptide sequence to be bolded, in HTML
  #<b>text</b>, so we split the last charater off and wrap it in the appropriate
  #tag and then toss out the columns it was split into
  separate(`Peptide Sequence`,into=c('start_pep','end_pep'),sep=-1) %>%
  mutate(`Peptide Sequence`=paste0(start_pep,'<b>',end_pep,'</b>')) %>%
  select(-start_pep,-end_pep) %>%
  
  #This split and rebuild then messes with the column order, so switch it back
  #to the original
  select(`Gene Symbol`,`Protein Name`,`Peptide Sequence`,everything()) %>%
  
  #Change these columns to the HTML equivalents
  rename(`LOD (fmol)<sup>2</sup>` = `LOD (fmol)2`) %>%
  rename(`LOQ (fmol)<sup>3</sup>` = `LOQ (fmol)3` )
  
#The first peptide entry needs some extra HTML markup, fix that here
curve_summary_output$`Peptide Sequence`[1] = "DTGELVAL<b>K</b><sup>1</sup>"
write_csv(curve_summary_output,here('simple_X_Y_figures/param_table.csv'))


pep_seq_table = read_excel(here('simple_XY/072919 file set/PEP-SEQ-TAB.xlsx'),skip=1) %>%
  #toss out any protein names that are NA, these are the notes at the end of the table
  filter(!is.na(`Protein Name`)) %>%
  
  #We need the last character of the peptide sequence to be bolded, in HTML
  #<b>text</b>, so we split the last charater off and wrap it in the appropriate
  #tag and then toss out the columns it was split into
  separate(`Peptide Sequence`,into=c('start_pep','end_pep'),sep=-1) %>%
  mutate(`Peptide Sequence`=paste0(start_pep,'<b>',end_pep,'</b>')) %>%
  select(-start_pep,-end_pep) %>%
  select(`Gene Symbol`, `Protein Name`, `Peptide Identifier`, `Peptide Sequence`)


#The first peptide entry needs some extra HTML markup, fix that here
pep_seq_table$`Peptide Sequence`[1] = "DTGELVAL<b>K</b><sup>1</sup>"
write_csv(pep_seq_table,here('simple_X_Y_figures/pep_seq_table.csv'))
```

# Plotting

```{r plot_reverse_curves, fig.width=6, fig.height=6}
deep_dive_reverse = deep_dive_data %>%
  filter(curve_type == "REV") %>%
  filter(!is.na(correlation_plot_slope))

reverse_curves = list()

# deep_dive_reverse = deep_dive_data %>%
#   filter(curve_type == "Reverse", peptide_start == "ISA")

reverse_curve_info = tibble(Gene = character(),
                            Peptide = character(),
                            Reverse_filename = character())

build_peptide_reverse_curve <- function(this_peptide_data) {

  
  intercept_text = ifelse(this_peptide_data$correlation_plot_intercept[1] > 0,
                          paste0("+",round(this_peptide_data$correlation_plot_intercept[1],3)),
                          round(this_peptide_data$correlation_plot_intercept[1],3))
  
  correlation_eq = paste0('y=',
                          round(this_peptide_data$correlation_plot_slope[1],3),
                          'x',
                          intercept_text)
  
  summary_text = paste0(this_peptide_data$kinase[1],"\n",this_peptide_data$peptide[1],"\n",correlation_eq)  
  
  full_range_plot <- ggplot(this_peptide_data,aes(x=Theor_conc,y=Meas_conc,shape=Ion)) +
    geom_point() +
    theme_berginski() +
    labs(x="Theoretical Concentration (fmol/\U00B5L)",y="Measured Concentration (fmol/\U00B5L)") +
    ggtitle(paste0('Calibration Curve for ',this_peptide_data$kinase[1] ,' Peptide')) +
    geom_abline(slope = this_peptide_data$correlation_plot_slope[1],
                intercept = this_peptide_data$correlation_plot_intercept[1],
                color='blue',
                lwd=1.5,
                alpha=0.75) +
    geom_abline(slope = 1, intercept = 0, lwd=1.5, alpha=0.75) +
    geom_text(aes(x = max(this_peptide_data$Theor_conc),
                  y = 1,
                  label = summary_text),
              hjust="inward",vjust="inward",size=8) +
    # theme(legend.position = "none") +
    NULL

  #The zoom plot should consist of the lowest three values in the full plot, that are above the limit of detection
  sorted_vals_above_lod = sort(unique(this_peptide_data$Theor_conc[which(this_peptide_data$Theor_conc > this_peptide_data$lod[1])]))
  if (length(sorted_vals_above_lod) >= 3) {
    low_val_min = sorted_vals_above_lod[3]
  } else {
    low_val_min = sorted_vals_above_lod[length(sorted_vals_above_lod)]
  }
  
  this_peptide_low_vals = this_peptide_data %>%
    filter(Theor_conc <= low_val_min)
  
  zoom_plot <- ggplot(this_peptide_low_vals,aes(x=Theor_conc,y=Meas_conc,shape=Ion)) +
    # geom_vline(xintercept = this_peptide_low_vals$lod[1], color='red') +
    geom_text(aes(x=this_peptide_low_vals$lod[1],
                  y=max(this_peptide_low_vals$Meas_conc),
                  label = paste0('LOD=',this_peptide_low_vals$lod[1],' fmol')),
              color='black',hjust="inward",vjust="inward",size=4) +
    geom_point() +
    theme_berginski() +
    labs(x="",y="") +
    geom_abline(slope = this_peptide_data$correlation_plot_slope[1],
                intercept = this_peptide_data$correlation_plot_intercept[1],
                color='blue',
                lwd=1.5,
                alpha=0.75) +
    geom_abline(slope = 1, intercept = 0, lwd=1.5, alpha=0.75) +
    theme(legend.position = "none") +
    NULL
  
  combined_plot <- ggdraw() +
    draw_plot(full_range_plot) +
    draw_plot(zoom_plot,x = 0.075,y = 0.5,width = 0.4,height = 0.4)
  return(combined_plot)
}

dir.create(here('simple_X_Y_figures'),showWarnings = F)
dir.create(here('simple_X_Y_figures','SVG'),showWarnings = F)
dir.create(here('simple_X_Y_figures','PNG'),showWarnings = F)
for (this_peptide in unique(deep_dive_reverse$peptide)) {
  this_peptide_data = deep_dive_reverse %>% filter(peptide == this_peptide)

  this_kinase = this_peptide_data$kinase[1]

  reverse_curves[[this_kinase]][[this_peptide]] <- build_peptide_reverse_curve(this_peptide_data)

  ggsave(here('simple_X_Y_figures','SVG',paste0(this_kinase,'-',this_peptide,'-Reverse.svg')),
         reverse_curves[[this_kinase]][[this_peptide]])
  ggsave(here('simple_X_Y_figures','PNG',paste0(this_kinase,'-',this_peptide,'-Reverse.png')),
         reverse_curves[[this_kinase]][[this_peptide]])
  
  reverse_curve_info = reverse_curve_info %>%
    add_row(Gene = this_kinase,
            Peptide = this_peptide,
            Reverse_filename = paste0(this_kinase,'-',this_peptide,'-Reverse.svg'))
}
write_csv(reverse_curve_info, here('simple_X_Y_figures/PRM_reverse_curve_data.csv'))
```

```{r plot_forward_curves}
deep_dive_forward = deep_dive_data %>%
  filter(curve_type == "FWD")

forward_curves = list()

build_peptide_forward_curve <- function(this_peptide_data) {
  this_peptide_summary = this_peptide_data %>% 
    group_by(Theor_conc) %>% 
    summarise(mean_measured = mean(Meas_conc),
              sd_measured = sd(Meas_conc))

  this_peptide_summary_low = this_peptide_summary %>%
    filter(Theor_conc <= sort(this_peptide_summary$Theor_conc)[3])

  intercept_text = ifelse(this_peptide_data$response_curve_intercept[1] > 0,
                          paste0("+",round(this_peptide_data$response_curve_intercept[1],3)),
                          round(this_peptide_data$response_curve_intercept[1],3))

  intercept_text = ifelse(as.numeric(intercept_text) == 0,
                          "",
                          intercept_text)
  
  correlation_eq = paste0('y=',
                          round(this_peptide_data$response_curve_slope[1],2),
                          'x',
                          intercept_text)
  
  summary_text = paste0(this_peptide_data$kinase[1],"\n",this_peptide_data$peptide[1],"\n",correlation_eq)  
  
  full_range_plot <- ggplot(this_peptide_summary,aes(x=Theor_conc,y=mean_measured)) +
    geom_point() +
    geom_errorbar(aes(ymin=mean_measured - sd_measured,ymax=mean_measured + sd_measured),
                  width=0.02*max(this_peptide_summary$Theor_conc)) +
    theme_berginski() +
    labs(x="Concentration (fmol/\U00B5L)",y="Average Peak Area Ratio") +
    ggtitle(paste0('Standard Response Curve for Absolute Quantification of ',this_peptide_data$kinase[1], " Peptide")) +
    geom_abline(slope = this_peptide_data$response_curve_slope[1],
                intercept = this_peptide_data$response_curve_intercept[1],
                lwd=1.5,
                alpha=0.75) +
        geom_text(aes(x = max(this_peptide_data$Theor_conc),
                  y = 1,
                  label = summary_text),
              hjust="inward",vjust="inward",size=8) +
    NULL
  

  zoom_plot <- ggplot(this_peptide_summary_low,aes(x=Theor_conc,y=mean_measured)) +
    geom_vline(xintercept = this_peptide_data$lod[1], color='red') +
    geom_text(aes(x = this_peptide_data$lod[1],
                  y = max(this_peptide_summary_low$mean_measured),
                  label = paste0('LOD=',this_peptide_data$lod[1])),
                  color='red',hjust="inward",vjust="inward",size=6) +
    geom_point() +
    geom_errorbar(aes(ymin=mean_measured - sd_measured,ymax=mean_measured + sd_measured),
                  width=0.02*max(this_peptide_summary_low$Theor_conc)) +
    theme_berginski() +
    labs(x="",y="") +
    geom_abline(slope = this_peptide_data$response_curve_slope[1],
                intercept = this_peptide_data$response_curve_intercept[1],
                lwd=1.5,
                alpha=0.75) +
    NULL

  combined_plot <- ggdraw() +
    draw_plot(full_range_plot) +
    draw_plot(zoom_plot,x = 0.075,y = 0.5,width = 0.4,height = 0.4)
  return(combined_plot)
}

dir.create(here('simple_X_Y_figures'),showWarnings = F)
for (this_peptide in unique(deep_dive_forward$peptide)) {
  this_peptide_data = deep_dive_forward %>% filter(peptide == this_peptide)

  this_kinase = this_peptide_data$kinase[1]

  forward_curves[[this_kinase]][[this_peptide]] <- build_peptide_forward_curve(this_peptide_data)
  curve_info = curve_info %>% add_row(Gene = this_kinase,
                                      Peptide = this_peptide,
                                      Reverse_filename = paste0(this_kinase,'-',this_peptide,'-Reverse.svg'),
                                      Forward_filename = paste0(this_kinase,'-',this_peptide,'-Forward.svg'))
  
  ggsave(here('simple_X_Y_figures','SVG',paste0(this_kinase,'-',this_peptide,'-Forward.svg')),
         forward_curves[[this_kinase]][[this_peptide]], width=7.75,height=7.75*3/4)
  ggsave(here('simple_X_Y_figures','PNG',paste0(this_kinase,'-',this_peptide,'-Forward.png')),
         forward_curves[[this_kinase]][[this_peptide]])
}

write_csv(curve_info,here('simple_X_Y_figures/PRM_curve_data.csv'))
```